name = "julia analysis code"
uuid = "1cd82d1a-be62-4394-bfc6-67c34366edc8"
authors = ["Fabian Zierler <fabian.zierler@a1.net>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
